package com.draculavenom.whatsapp.enums;

public enum BotState {
    START,
    MAIN_MENU,

    BOOKING_SUGGEST,
    BOOKING_DATE,
    BOOKING_TIME,
    BOOKING_CONFIRM,

    CANCEL_SELECT,
    CANCEL_REASON,
    CANCEL_CONFIRM,

    REGISTER_FIRST_NAME,
    REGISTER_LAST_NAME,
    REGISTER_DAY_BIRTH,
    REGISTER_EMAIL,
    REGISTER_CONFIRM
}
